// magic constants that's auto-generated by Forge's Vite plugin
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;


declare interface Window {
    electron: unknown;
    versions: unknown;
}
